import type { CollectionConfig } from 'payload'

export const Articles: CollectionConfig = {
  slug: 'articles',
  admin: {
    useAsTitle: 'title',
    group: '内容',
    defaultColumns: ['title', 'status', 'author', 'category', 'publishedAt'],
  },
  access: {
    read: () => true,
    create: ({ req }) => Boolean(req.user),
    update: ({ req }) => Boolean(req.user),
    delete: ({ req }) => Boolean(req.user),
  },
  versions: { drafts: true },
  fields: [
    { name: 'title', type: 'text', required: true, label: '标题' },
    { name: 'slug', type: 'text', required: true, unique: true, label: 'Slug' },
    { name: 'excerpt', type: 'textarea', label: '摘要' },
    { name: 'content', type: 'richText', label: '正文' },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'draft',
      options: [
        { label: '草稿', value: 'draft' },
        { label: '待审核', value: 'pending-review' },
        { label: '已发布', value: 'published' },
        { label: '已归档', value: 'archived' },
      ],
      admin: { position: 'sidebar' },
      label: '状态',
    },
    {
      name: 'reviewStatus',
      type: 'select',
      defaultValue: 'unreviewed',
      options: [
        { label: '未审核', value: 'unreviewed' },
        { label: '审核通过', value: 'approved' },
        { label: '审核驳回', value: 'rejected' },
      ],
      admin: { position: 'sidebar' },
      label: '审核状态',
    },
    {
      name: 'author',
      type: 'relationship',
      relationTo: 'authors',
      label: '作者',
      admin: { position: 'sidebar' },
    },
    {
      name: 'category',
      type: 'relationship',
      relationTo: 'categories',
      label: '分类',
      admin: { position: 'sidebar' },
    },
    {
      name: 'keywords',
      type: 'relationship',
      relationTo: 'keywords',
      hasMany: true,
      label: '关键词',
    },
    {
      name: 'coverImage',
      type: 'upload',
      relationTo: 'images',
      label: '封面图',
      admin: { position: 'sidebar' },
    },
    {
      name: 'inlineImages',
      type: 'relationship',
      relationTo: 'images',
      hasMany: true,
      label: '内容图片',
    },
    {
      name: 'seo',
      type: 'group',
      label: 'SEO',
      fields: [
        { name: 'metaTitle', type: 'text' },
        { name: 'metaDescription', type: 'textarea' },
        { name: 'metaKeywords', type: 'text' },
        { name: 'ogImage', type: 'upload', relationTo: 'images' },
      ],
    },
    {
      name: 'isAiGenerated',
      type: 'checkbox',
      defaultValue: false,
      label: 'AI 生成',
      admin: { position: 'sidebar' },
    },
    {
      name: 'isFeatured',
      type: 'checkbox',
      defaultValue: false,
      label: '推荐',
      admin: { position: 'sidebar' },
    },
    {
      name: 'isHot',
      type: 'checkbox',
      defaultValue: false,
      label: '热门',
      admin: { position: 'sidebar' },
    },
    {
      name: 'sourceTask',
      type: 'relationship',
      relationTo: 'tasks',
      label: '来源任务',
      admin: { position: 'sidebar', readOnly: true },
    },
    {
      name: 'sourceTitle',
      type: 'relationship',
      relationTo: 'titles',
      label: '来源标题',
      admin: { position: 'sidebar', readOnly: true },
    },
    {
      name: 'viewCount',
      type: 'number',
      defaultValue: 0,
      admin: { readOnly: true, position: 'sidebar' },
      label: '浏览数',
    },
    { name: 'publishedAt', type: 'date', admin: { position: 'sidebar' }, label: '发布时间' },
  ],
}
